language: python

# required for python 3.7 support
dist: xenial
python:
  - "3.7"

cache:
  pip: true

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  
# command to run tests, capture coverage stats and push those stats to codecov.io
script:
  - poetry run coverage run manage.py test
  - codecov
