language: python

dist: xenial
python:
  - "3.6"

cache:
  pip: true

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  
# Run tests and capture coverage stats
script:
  - poetry run coverage run manage.py test

# Push those stats to codecov.io
after_success:
  - codecov
