language: python

# required for python 3.7 support
dist: xenial
python:
  - "3.7"

cache:
  pip: true

# Ensure pre-requisite of psycopg2 Python package is installed
before_install:
  - sudo apt-get install -y libpq-dev

# Install dependencies
install:
  - pip install poetry
  - poetry install -E pgsql -E gunicorn
  
# Run tests and capture coverage stats
script:
  - poetry run coverage run manage.py test

# Push those stats to codecov.io
after_success:
  - codecov
