language: python

# required for python 3.7 support
dist: xenial
python:
  - "3.7"

cache:
  pip: true

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  
# Run tests and capture coverage stats
script:
  - poetry run coverage run manage.py test

# Push those stats to codecov.io
after_success:
  - codecov
