language: python

# required for python 3.7 support
dist: xenial
python:
  - "3.7"

addons: # get google-chrome-stable for selernium testing
  chrome: stable

cache:
  pip: true

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  # Install ChromeDriver 
  - wget -N https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  
# command to run tests, capture coverage stats and push those stats to codecov.io
script:
  - poetry run coverage run manage.py test
  - codecov
