# Generated by Django 3.2.11 on 2022-08-25 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('P', 'Mathematical, Physical & Life Sciences Division'), ('M', 'Medical Science Division'), ('H', 'Humanities Division'), ('S', 'Social Sciences Divsion')], max_length=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('proj_costing_id', models.CharField(max_length=50, null=True)),
                ('funder_ref', models.CharField(max_length=50, null=True)),
                ('grant_number', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('internal', models.BooleanField(default=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Preparation'), ('R', 'Review'), ('F', 'Funded'), ('X', 'Rejected')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rse.client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_rse.project_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_until', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=1)),
                ('grade_point', models.IntegerField(default=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('increments', models.BooleanField(default=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rse.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rse.project')),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('staff_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('overheads', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rse.project',),
        ),
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rse.project')),
                ('days', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('charged', models.BooleanField(default=True)),
                ('invoice_received', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rse.project',),
        ),
        migrations.CreateModel(
            name='SalaryGradeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.rse')),
                ('salary_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rse.salaryband')),
            ],
        ),
        migrations.CreateModel(
            name='RSEAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.project')),
                ('rse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.rse')),
            ],
        ),
    ]
