# Generated by Django 3.2.11 on 2022-08-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.project')),
                ('rse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rse.rse')),
            ],
        ),
    ]
